-- 테이블 생성
CREATE TABLE MEMBERS (
    MEMBERS_ID NUMBER,
    STATUS      NUMBER(1) NOT NULL,
    CARD_NUM    VARCHAR2(15),
    EMAIL       VARCHAR2(50)   NOT NULL,
    PASSWORD    VARCHAR2(20)   NOT NULL,
    NAME        VARCHAR2(30)   NOT NULL,
    MOBILE      VARCHAR2(20)   NOT NULL,
    ZIPCODE     VARCHAR2(10)   NOT NULL,
    ADDRESS     VARCHAR2(100)  NOT NULL,
    JOIN_DATE   DATE           NOT NULL,
    LEAVE_DATE  DATE,
    
    CONSTRAINT PK_MEMBERS PRIMARY KEY (MEMBERS_ID)
);

-- 시퀀스 생성
CREATE SEQUENCE SQ_MEMBERS
START WITH 1
INCREMENT BY 1
NOMAXVALUE
NOCYCLE
NOCACHE;

-- 테이블 전체 조회
SELECT * FROM MEMBERS;

-- 예제 데이터 추가
INSERT INTO MEMBERS (MEMBERS_ID, STATUS, CARD_NUM, EMAIL, PASSWORD, NAME, MOBILE, ZIPCODE, ADDRESS, JOIN_DATE, LEAVE_DATE)
VALUES (SQ_MEMBERS.NEXTVAL, 0, null, 'test1@test.com', 'test1', '가길동', '010-1234-5678', '12345', '서울특별시 강남구 테헤란로 123', SYSDATE, null);

INSERT INTO MEMBERS (MEMBERS_ID, STATUS, CARD_NUM, EMAIL, PASSWORD, NAME, MOBILE, ZIPCODE, ADDRESS, JOIN_DATE, LEAVE_DATE)
VALUES (SQ_MEMBERS.NEXTVAL, 1, null, 'test2@test.com', 'test2', '나길동', '010-5678-9001', '12445', '부산광역시 해운대구 해운대로 456 ', SYSDATE, null);

INSERT INTO MEMBERS (MEMBERS_ID, STATUS, CARD_NUM, EMAIL, PASSWORD, NAME, MOBILE, ZIPCODE, ADDRESS, JOIN_DATE, LEAVE_DATE)
VALUES (SQ_MEMBERS.NEXTVAL, 2, null, 'test3@test.com', 'test3', '다길동', '010-0000-0002', '12445', '인천광역시 연수구 송도대로 101', SYSDATE, null);


-- 시퀀스 전체 조회
SELECT * FROM user_sequences;

-- 시퀀스 삭제
DROP SEQUENCE SQ_MEMBERS;

-- 테이블 내용 전체 삭제
TRUNCATE TABLE MEMBERS;

-- 테이블 제거
DROP TABLE MEMBERS;

-- 테이블 fk 함께 삭제
DROP TABLE RECO_BOOKS CASCADE CONSTRAINTS;



