-- 테이블 생성
CREATE TABLE JWT_REFRESH (
  JWT_REFRESH_ID  NUMBER,                                -- 리프레시 토큰 ID
  MEMBERS_ID      NUMBER,                                -- 회원정보 ID: MEMBERS.MEMBERS_ID
  REFRESH_TOKEN   VARCHAR2(500)     NOT NULL,            -- 리프레시 토큰
  EXPIRES_DATE    DATE              NOT NULL,            -- 만료시간

  -- 제약조건
  CONSTRAINT PK_JWT_REFRESH PRIMARY KEY (JWT_REFRESH_ID),
  CONSTRAINT FK_JWT_REFRESH_MEM_MEMBERINFO FOREIGN KEY (MEMBERS_ID)
    REFERENCES MEMBERS(MEMBERS_ID)
);

-- 시퀀스 생성
CREATE SEQUENCE SQ_JWT_REFRESH
START WITH 1
INCREMENT BY 1
NOMAXVALUE
NOCYCLE
NOCACHE;