-- 테이블 생성
CREATE TABLE MEMBERS (
    MEMBERS_ID NUMBER,
    USERNAME	VARCHAR2(20)	NOT NULL,
    PASSWORD    VARCHAR2(100)	NOT NULL,
    
    NAME        VARCHAR2(30)	NOT NULL,
    EMAIL       VARCHAR2(50)	NOT NULL,
    MOBILE      VARCHAR2(20)	NOT NULL,
    ZIPCODE     VARCHAR2(10)	NOT NULL,
    ADDRESS     VARCHAR2(100)	NOT NULL,
    ADDRESS_DETAIL     VARCHAR2(100)	NOT NULL,
    
    STATUS      NUMBER(1)		NOT NULL, -- 상태: 0-준회원, 1-정회원, 2-대출정지(연체), 3-탈퇴, ..., 9-관리자
    CARD_NUM    VARCHAR2(15),
    LOAN_COUNT      NUMBER(1)	NOT NULL,

    JOIN_DATE   DATE			NOT NULL,
    LEAVE_DATE  DATE,
    
    CONSTRAINT PK_MEMBERS PRIMARY KEY (MEMBERS_ID)
);

-- 시퀀스 생성
CREATE SEQUENCE SQ_MEMBERS
START WITH 1
INCREMENT BY 1
NOMAXVALUE
NOCYCLE
NOCACHE;

-- 테이블 전체 조회
SELECT * FROM MEMBERS;

-- 예제 데이터 추가
INSERT INTO MEMBERS (
    MEMBERS_ID, USERNAME, PASSWORD, 
    NAME, EMAIL, MOBILE, ZIPCODE, ADDRESS, ADDRESS_DETAIL, 
    STATUS, CARD_NUM, LOAN_COUNT,
    JOIN_DATE, LEAVE_DATE
) VALUES (
    0,  'admin', '{bcrypt}$2a$10$xFP4Nsk0kAag4QsQ1FnMzeh3TyJMjf96q5VKNg5fKv410DRnUtj1e', 
    '관리자', 'globlainlibrary@gmail.com', '02-0000-0000', '12345', '서울특별시 영등포구 가나다로 1', '글로벌인 도서관', 
    9, NULL, 0,
    TO_DATE('2025-06-01', 'YYYY-MM-DD'), NULL
);

INSERT INTO MEMBERS (
    MEMBERS_ID, USERNAME, PASSWORD, 
    NAME, EMAIL, MOBILE, ZIPCODE, ADDRESS, ADDRESS_DETAIL, 
    STATUS, CARD_NUM, LOAN_COUNT,
    JOIN_DATE, LEAVE_DATE
) VALUES (
    SQ_MEMBERS.NEXTVAL,  'test1', '{bcrypt}$2a$10$ua44FxKRU5WTtchn7IbiJ.iQkDcVWnMlbwVjoQM/WJnXO1EgnT5ou', 
    '가길동', 'test1@test.com', '010-1234-5678', '12345', '서울시 강남구 가나다로 1', '삼성아파트 1401호', 
    3, NULL, 0,
    TO_DATE('2025-05-30', 'YYYY-MM-DD'), TO_DATE('2025-08-01', 'YYYY-MM-DD')
);

INSERT INTO MEMBERS (
    MEMBERS_ID, USERNAME, PASSWORD, 
    NAME, EMAIL, MOBILE, ZIPCODE, ADDRESS, ADDRESS_DETAIL, 
    STATUS, CARD_NUM, LOAN_COUNT,
    JOIN_DATE, LEAVE_DATE
) VALUES (
    SQ_MEMBERS.NEXTVAL, 'test11', '{bcrypt}$2a$10$6HPrED.4NEZstkgntxlG/eanPEKWd6tysZTNogEM.BWH9DsOzppEC', 
    '김철수', 'test11@gmail.com', '010-1111-2222', '06236', '서울 강남구 테헤란로 100', '101호', 
     0, NULL, 0,
    TO_DATE('2025-05-01', 'YYYY-MM-DD'), NULL
);

INSERT INTO MEMBERS (
    MEMBERS_ID, USERNAME, PASSWORD, 
    NAME, EMAIL, MOBILE, ZIPCODE, ADDRESS, ADDRESS_DETAIL, 
    STATUS, CARD_NUM,  LOAN_COUNT,
    JOIN_DATE, LEAVE_DATE
) VALUES (
    SQ_MEMBERS.NEXTVAL, 'test2', '{bcrypt}$2a$10$w1/LYgX.LMMgDKgQxuIel.E8NYG97r1AMyIZtkN2a6dx/GS.zeMjK', 
    '이영희', 'test2@test.com', '010-3333-4444', '13589', '부산 해운대구 해운대로 300', '301호', 
    2, '20250601-003330', 0,
    TO_DATE('2025-02-15', 'YYYY-MM-DD'), NULL
);

INSERT INTO MEMBERS (
    MEMBERS_ID, USERNAME, PASSWORD, 
    NAME, EMAIL, MOBILE, ZIPCODE, ADDRESS, ADDRESS_DETAIL, 
    STATUS, CARD_NUM, LOAN_COUNT,
    JOIN_DATE, LEAVE_DATE
) VALUES (
    SQ_MEMBERS.NEXTVAL, 'test3', '{bcrypt}$2a$10$LYRqyKMSv2ugc3VYHn5Jr.Sl7Vxf3touuL2YLLVV5dGU6rTtaP/IO', 
    '박민수', 'test3@test.com', '010-5555-6666', '04567', '대구 중구 중앙대로 50', '501호', 
    0, NULL, 0,
    TO_DATE('2025-03-22', 'YYYY-MM-DD'), NULL
);

INSERT INTO MEMBERS (
    MEMBERS_ID, USERNAME, PASSWORD, 
    NAME, EMAIL, MOBILE, ZIPCODE, ADDRESS, ADDRESS_DETAIL, 
    STATUS, CARD_NUM, LOAN_COUNT,
    JOIN_DATE, LEAVE_DATE
) VALUES (
    SQ_MEMBERS.NEXTVAL, 'test4', '{bcrypt}$2a$10$BwHm5N0nJxwqUIrvOGXgmuMLYIQzEbaMeIjjZY3nmAVdLcW5zvb/2', 
    '정소영', 'test4@naver.com', '010-7777-8888', '06789', '광주 북구 첨단대로 90', '901호', 
    1, '20250530-777777', 0,
    TO_DATE('2025-01-10', 'YYYY-MM-DD'), NULL
);


-- 시퀀스 전체 조회
SELECT * FROM user_sequences;

-- 시퀀스 삭제
DROP SEQUENCE SQ_MEMBERS;

-- 테이블 내용 전체 삭제
TRUNCATE TABLE MEMBERS;

-- 테이블 제거
DROP TABLE MEMBERS;

-- 테이블 fk 함께 삭제
DROP TABLE MEMBERS CASCADE CONSTRAINTS;



