-- 테이블 생성
CREATE TABLE REPLIES (
  REPLIES_ID         NUMBER,                              						-- 게시글댓글ID
  ORIGIN_ARTICLE_ID  NUMBER,                              						-- 원본 게시글 ID (ARTICLES.ARTICLES_ID)
  AUTHOR_ID          NUMBER,                              						-- 작성자 ID (MEMBERS.MEMBER_ID)
  CONTENT            VARCHAR2(500)       NOT NULL,                              -- 내용
  CREATE_DATE        DATE                DEFAULT SYSDATE NOT NULL,              -- 등록일자
  UPDATE_DATE        DATE				 NOT NULL,                              -- 수정일자

  -- 제약조건
  CONSTRAINT PK_REPLIES PRIMARY KEY (REPLIES_ID),
  CONSTRAINT FK_REPLIES_MEMBERS_AUTHOR FOREIGN KEY (AUTHOR_ID)
    REFERENCES MEMBERS(MEMBERS_ID),
  CONSTRAINT FK_REPLIES_ARTICLES_ORG_ART FOREIGN KEY (ORIGIN_ARTICLE_ID)
    REFERENCES ARTICLES(ARTICLES_ID)
    ON DELETE CASCADE
);

-- 시퀀스 생성
CREATE SEQUENCE SQ_REPLIES
START WITH 1
INCREMENT BY 1
NOMAXVALUE
NOCYCLE
NOCACHE;



-- 테스트
-- 댓글 데이터 삽입
INSERT INTO REPLIES (REPLIES_ID, ORIGIN_ARTICLE_ID, AUTHOR_ID, CONTENT, CREATE_DATE, UPDATE_DATE)
VALUES 
(SQ_REPLIES.nextval, 2, 2, '공지사항 확인했습니다! 점검 후 기대되네요.', SYSDATE, SYSDATE);

INSERT INTO REPLIES (REPLIES_ID, ORIGIN_ARTICLE_ID, AUTHOR_ID, CONTENT, CREATE_DATE, UPDATE_DATE)
VALUES
(SQ_REPLIES.nextval, 2, 3, '새로운 기능 너무 좋네요! 자세한 안내 부탁드립니다.', SYSDATE, SYSDATE);

INSERT INTO REPLIES (REPLIES_ID, ORIGIN_ARTICLE_ID, AUTHOR_ID, CONTENT, CREATE_DATE, UPDATE_DATE)
VALUES
(SQ_REPLIES.nextval, 3, 4, '이벤트 기대됩니다! 참여 방법은 언제 올라오나요?', SYSDATE, SYSDATE);

INSERT INTO REPLIES (REPLIES_ID, ORIGIN_ARTICLE_ID, AUTHOR_ID, CONTENT, CREATE_DATE, UPDATE_DATE)
VALUES
(SQ_REPLIES.nextval, 4, 5, '정책 변경 사항을 잘 확인해야겠네요.', SYSDATE, SYSDATE);

INSERT INTO REPLIES (REPLIES_ID, ORIGIN_ARTICLE_ID, AUTHOR_ID, CONTENT, CREATE_DATE, UPDATE_DATE)
VALUES
(SQ_REPLIES.nextval, 5, 6, '서버 업그레이드라니! 더 빠른 서비스 기대할게요.', SYSDATE, SYSDATE);


  
-- 인덱스 생성
CREATE INDEX IDX_REPLIES_CONTENT      ON REPLIES (CONTENT);        -- 내용 키워드 탐색
CREATE INDEX IDX_REPLIES_CREATE_DATE  ON REPLIES (CREATE_DATE);    -- 등록일 정렬
