-- 테이블 생성
CREATE TABLE BOOK_HISTORY (
  BOOK_HISTORY_ID  NUMBER,              -- 관심 도서 ID
  MEMBERS_ID       NUMBER,              -- 대상 회원: MEMBERS.MEMBERS_ID
  BOOKS_ID         NUMBER,              -- 대상 도서: BOOKS.BOOKS_ID
  LOAN_DATE        DATE       NOT NULL, -- 대출일자
  DUE_DATE         DATE		  NOT NULL, -- 반납예정일자
  RETURNED_DATE    DATE		  NOT NULL,	-- 반납완료일자
  IS_OVERDUE       BOOLEAN    NOT NULL, -- 연체여부: F(정상), T(연체)

  -- 제약조건
  CONSTRAINT PK_BOOK_HISTORY PRIMARY KEY (BOOK_HISTORY_ID),
  CONSTRAINT FK_BOOK_HIS_BOOKS_BOOKSINFO FOREIGN KEY (BOOKS_ID)
    REFERENCES BOOKS(BOOKS_ID),
  CONSTRAINT FK_BOOK_HISTORY_MEMBERS_AUTHOR FOREIGN KEY (MEMBERS_ID)
    REFERENCES MEMBERS(MEMBERS_ID)
);

-- 시퀀스 생성
CREATE SEQUENCE SQ_BOOK_HISTORY
START WITH 1
INCREMENT BY 1
NOMAXVALUE
NOCYCLE
NOCACHE;


-- 예제

-- 인덱스 생성
CREATE INDEX IDX_BOOK_HISTORY_RENT_DATE   ON BOOK_HISTORY (LOAN_DATE);   -- 대여날짜순 정렬
CREATE INDEX IDX_BOOK_HISTORY_DUE_DATE    ON BOOK_HISTORY (DUE_DATE);    -- 반납예정일자순 정렬
CREATE INDEX IDX_BOOK_HISTORY_IS_OVERDUE  ON BOOK_HISTORY (IS_OVERDUE);  -- 연체여부 필터