-- 테이블 생성
CREATE TABLE BOOK_LIKE (
  BOOK_LIKE_ID  NUMBER,                 -- 도서이용정보ID
  MEMBERS_ID       NUMBER,              -- 대상 회원: MEMBERS.MEMBERS_ID
  BOOKS_ID         NUMBER,              -- 대상 도서: BOOKS.BOOKS_ID
  LOAN_DATE        DATE       NOT NULL, -- 관심도서로 저장한 날짜

  -- 제약조건
  CONSTRAINT PK_BOOK_LIKE PRIMARY KEY (BOOK_LIKE_ID),
  CONSTRAINT FK_BOOK_LIKE_BOOKS_INFO FOREIGN KEY (BOOKS_ID)
    REFERENCES BOOKS(BOOKS_ID),
  CONSTRAINT FK_BOOK_LIKE_MEMBERS_INFO FOREIGN KEY (MEMBERS_ID)
    REFERENCES MEMBERS(MEMBERS_ID)
);

-- 시퀀스 생성
CREATE SEQUENCE SQ_BOOK_LIKE
START WITH 1
INCREMENT BY 1
NOMAXVALUE
NOCYCLE
NOCACHE;

-- 예제