-- 테이블 생성
CREATE TABLE BOOK_REQ (
  BOOK_REQ_ID   NUMBER,             -- 희망 도서 신청 ID
  MEMBERS_ID    NUMBER,             -- 대상 회원: MEMBERS.MEMBERS_ID
  ARTICLES_ID   NUMBER,             -- 원본글: ARTICLES.ARTICLES_ID
  STATUS        NUMBER    NOT NULL, -- 상태: 0-접수, 1-처리중, 2-처리완료

  -- 제약조건
  CONSTRAINT PK_BOOK_REQ PRIMARY KEY (BOOK_REQ_ID),
  CONSTRAINT FK_BOOK_REQ_MEMBERS_INFO FOREIGN KEY (MEMBERS_ID)
    REFERENCES MEMBERS(MEMBERS_ID),
  CONSTRAINT FK_BOOK_REQ_ARTICLES_INFO FOREIGN KEY (ARTICLES_ID)
    REFERENCES ARTICLES(ARTICLES_ID)
);

-- 시퀀스 생성
CREATE SEQUENCE BOOK_REQ
START WITH 1
INCREMENT BY 1
NOMAXVALUE
NOCYCLE
NOCACHE;

-- 예제