-- 테이블 생성
CREATE TABLE BOOK_REVIEWS (
  BOOK_REVIEWS_ID  NUMBER,                                			-- 도서리뷰ID
  BOOKS_ID         NUMBER,                                			-- 리뷰 대상 도서: BOOKS.BOOKS_ID
  AUTHOR_ID        NUMBER,                                			-- 리뷰 작성자: MEMBERS.MEMBERS_ID
  CONTENT          VARCHAR2(500)      NOT NULL,           			-- 내용
  CREATE_DATE      DATE               DEFAULT SYSDATE NOT NULL, 	-- 등록날짜
  UPDATE_DATE      DATE,                                   			-- 수정날짜

  -- 제약조건
  CONSTRAINT PK_BOOK_REVIEWS PRIMARY KEY (BOOK_REVIEWS_ID),
  CONSTRAINT FK_BOOK_REVIEWS_BOOKINFO FOREIGN KEY (BOOKS_ID)
    REFERENCES BOOKS(BOOKS_ID) ON DELETE CASCADE,
  CONSTRAINT FK_BOOK_REVIEWS_MEMBERS_AUTHOR FOREIGN KEY (AUTHOR_ID)
    REFERENCES MEMBERS(MEMBERS_ID)
);

-- 인덱스 생성
CREATE INDEX IDX_BOOK_REVIEWS_CREATE_DATE ON BOOK_REVIEWS (CREATE_DATE); -- 등록일자 정렬용 인덱스

-- 시퀀스 생성
CREATE SEQUENCE SQ_BOOK_REVIEWS
START WITH 1
INCREMENT BY 1
NOMAXVALUE
NOCYCLE
NOCACHE;