-- 테이블 생성
CREATE TABLE RECO_BOOKS (
  RECO_BOOKS_ID  NUMBER,    -- 추천도서 ID
  BOOKS_ID       NUMBER,    -- 도서 ID: BOOKS.BOOKS_ID
  RECO_DATE      DATE       -- 추천한 날짜

  -- 제약조건
  CONSTRAINT PK_RECO_BOOKS PRIMARY KEY (RECO_BOOKS_ID),
  CONSTRAINT FK_RECO_BOOKS_BOOKINFO FOREIGN KEY (BOOKS_ID)
    REFERENCES BOOKS(BOOKS_ID)
);

-- 시퀀스 생성
CREATE SEQUENCE SQ_RECO_BOOKS
START WITH 1
INCREMENT BY 1
NOMAXVALUE
NOCYCLE
NOCACHE;
 
