-- 테이블 생성
CREATE TABLE BLACKLISTED_TOKEN (
	BLACKLISTED_TOKEN_ID   NUMBER,					-- 차단된 토큰 ID
	TYPE               NUMBER(1)     NOT NULL,		-- 타입: 액세스토큰, 리프레시토큰
	TOKEN              VARCHAR2(500)    NOT NULL,	-- 토큰 문자열
	EXPIRES_DATE       DATE             NOT NULL,	-- 만료시간

	-- 제약조건
  	CONSTRAINT PK_BLACKLISTED_TOKEN PRIMARY KEY (BLACKLISTED_TOKEN_ID)
);

-- 시퀀스 생성
CREATE SEQUENCE SQ_BLACKLISTED_TOKEN
START WITH 1
INCREMENT BY 1
NOMAXVALUE
NOCYCLE
NOCACHE;


-- 테스트
INSERT INTO BLACKLISTED_TOKEN (BLACKLISTED_TOKEN_ID, TYPE, TOKEN, EXPIRES_DATE)
VALUES (SQ_BLACKLISTED_TOKEN.NEXTVAL, 0, 'expired_access_token_123', TO_DATE('2025-06-04 12:00:00', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO BLACKLISTED_TOKEN (BLACKLISTED_TOKEN_ID, TYPE, TOKEN, EXPIRES_DATE)
VALUES (SQ_BLACKLISTED_TOKEN.NEXTVAL, 1, 'expired_refresh_token_456', TO_DATE('2025-06-05 15:30:00', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO BLACKLISTED_TOKEN (BLACKLISTED_TOKEN_ID, TYPE, TOKEN, EXPIRES_DATE)
VALUES (SQ_BLACKLISTED_TOKEN.NEXTVAL, 0, 'expired_access_token_789', TO_DATE('2025-06-03 18:45:00', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO BLACKLISTED_TOKEN (BLACKLISTED_TOKEN_ID, TYPE, TOKEN, EXPIRES_DATE)
VALUES (SQ_BLACKLISTED_TOKEN.NEXTVAL, 1, 'valid_refresh_token_abc', TO_DATE('2025-06-14 08:00:00', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO BLACKLISTED_TOKEN (BLACKLISTED_TOKEN_ID, TYPE, TOKEN, EXPIRES_DATE)
VALUES (SQ_BLACKLISTED_TOKEN.NEXTVAL, 1, 'valid_refresh_token_def', TO_DATE('2025-06-14 20:20:00', 'YYYY-MM-DD HH24:MI:SS'));