-- 테이블 생성
CREATE TABLE BLACKLISTED_TOKEN (
	BLACKLISTED_TOKEN_ID   NUMBER,				-- 차단된 토큰 ID
	TYPE			NUMBER(1)		NOT NULL,	-- 타입: 액세스토큰, 리프레시토큰
	TOKEN			VARCHAR2(300)	NOT NULL,	-- 토큰 문자열
	EXPIRES_DATE	DATE			NOT NULL,	-- 만료시간

	-- 제약조건
  	CONSTRAINT PK_BLACKLISTED_TOKEN PRIMARY KEY (BLACKLISTED_TOKEN_ID)
);

-- 시퀀스 생성
CREATE SEQUENCE SQ_BLACKLISTED_TOKEN
START WITH 1
INCREMENT BY 1
NOMAXVALUE
NOCYCLE
NOCACHE;


-- 테스트
