-- 테이블 생성
CREATE TABLE REFRESH_TOKEN (
	REFRESH_TOKEN_ID  NUMBER,					-- 리프레시 토큰 ID
	MEMBERS_ID		NUMBER,						-- 회원 ID: MEMBERS.MEMBERS_ID
	REFRESH_TOKEN   VARCHAR2(500)	NOT NULL,	-- 리프레시 토큰
	EXPIRES_DATE    DATE			NOT NULL,	-- 만료시간

	-- 제약조건
	CONSTRAINT PK_REFRESH_TOKEN PRIMARY KEY (REFRESH_TOKEN_ID),
	CONSTRAINT FK_REFRESH_TOKEN_MEMBERS_ID FOREIGN KEY (MEMBERS_ID) 
		REFERENCES MEMBERS(MEMBERS_ID) ON DELETE CASCADE;
);

-- 시퀀스 생성
CREATE SEQUENCE SQ_REFRESH_TOKEN
START WITH 1
INCREMENT BY 1
NOMAXVALUE
NOCYCLE
NOCACHE;