-- 테이블 생성
CREATE TABLE MEMBERS (
    MEMBERS_ID NUMBER,
    STATUS      NUMBER(1)		NOT NULL,
    CARD_NUM    VARCHAR2(15),
    USERNAME	VARCHAR2(20)	NOT NULL,
    PASSWORD    VARCHAR2(20)	NOT NULL,
    NAME        VARCHAR2(30)	NOT NULL,
    EMAIL       VARCHAR2(50)	NOT NULL,
    MOBILE      VARCHAR2(20)	NOT NULL,
    ZIPCODE     VARCHAR2(10)	NOT NULL,
    ADDRESS     VARCHAR2(100)	NOT NULL,
    JOIN_DATE   DATE			NOT NULL,
    LEAVE_DATE  DATE,
    
    CONSTRAINT PK_MEMBERS PRIMARY KEY (MEMBERS_ID)
);

-- 시퀀스 생성
CREATE SEQUENCE SQ_MEMBERS
START WITH 1
INCREMENT BY 1
NOMAXVALUE
NOCYCLE
NOCACHE;

-- 테이블 전체 조회
SELECT * FROM MEMBERS;

-- 예제 데이터 추가
INSERT INTO MEMBERS (MEMBERS_ID, STATUS, CARD_NUM, USERNAME, PASSWORD, NAME, EMAIL, MOBILE, ZIPCODE, ADDRESS, JOIN_DATE, LEAVE_DATE)
VALUES (SQ_MEMBERS.NEXTVAL, 0, null, 'test1', 'test1', '가길동', 'test1@test.com', '010-1234-5678', '12345', '서울특별시 강남구 테헤란로 123', SYSDATE, null);

INSERT INTO MEMBERS (MEMBERS_ID, STATUS, CARD_NUM, USERNAME, PASSWORD, NAME, EMAIL, MOBILE, ZIPCODE, ADDRESS, JOIN_DATE, LEAVE_DATE)
VALUES (SQ_MEMBERS.NEXTVAL, 0, null, 'test2', 'test2', '나길동', 'test2@test.com', '010-2345-6789', '23456', '서울특별시 서초구 반포대로 45', SYSDATE, null);

INSERT INTO MEMBERS (MEMBERS_ID, STATUS, CARD_NUM, USERNAME, PASSWORD, NAME, EMAIL, MOBILE, ZIPCODE, ADDRESS, JOIN_DATE, LEAVE_DATE)
VALUES (SQ_MEMBERS.NEXTVAL, 0, null, 'test3', 'test3', '다길동', 'test3@test.com', '010-3456-7890', '34567', '서울특별시 종로구 새문안로 98', SYSDATE, null);

INSERT INTO MEMBERS (MEMBERS_ID, STATUS, CARD_NUM, USERNAME, PASSWORD, NAME, EMAIL, MOBILE, ZIPCODE, ADDRESS, JOIN_DATE, LEAVE_DATE)
VALUES (SQ_MEMBERS.NEXTVAL, 0, null, 'test4', 'test4', '라길동', 'test4@test.com', '010-4567-8901', '45678', '서울특별시 마포구 독막로 12', SYSDATE, null);

INSERT INTO MEMBERS (MEMBERS_ID, STATUS, CARD_NUM, USERNAME, PASSWORD, NAME, EMAIL, MOBILE, ZIPCODE, ADDRESS, JOIN_DATE, LEAVE_DATE)
VALUES (SQ_MEMBERS.NEXTVAL, 0, null, 'test5', 'test5', '마길동', 'test5@test.com', '010-5678-9012', '56789', '서울특별시 송파구 올림픽로 78', SYSDATE, null);


-- 시퀀스 전체 조회
SELECT * FROM user_sequences;

-- 시퀀스 삭제
DROP SEQUENCE SQ_MEMBERS;

-- 테이블 내용 전체 삭제
TRUNCATE TABLE MEMBERS;

-- 테이블 제거
DROP TABLE MEMBERS;

-- 테이블 fk 함께 삭제
DROP TABLE MEMBERS CASCADE CONSTRAINTS;



