-- 테이블 생성
CREATE TABLE BOOK_HISTORY (
  BOOK_HISTORY_ID  NUMBER,                                         -- 도서이용정보ID
  BOOKS_ID         NUMBER,                                         -- 대상 도서: BOOKS.BOOKS_ID
  MEMBERS_ID       NUMBER,                                         -- 대상 회원: MEMBERS.MEMBERS_ID
  LOAN_DATE        DATE            	DEFAULT SYSDATE NOT NULL,      -- 대출일자
  DUE_DATE         DATE				NOT NULL,                      -- 반납예정일자
  IS_OVERDUE       NUMBER(1)        DEFAULT 0 NOT NULL,            -- 연체여부: 0(정상), 1(연체)

  -- 제약조건
  CONSTRAINT PK_BOOK_HISTORY PRIMARY KEY (BOOK_HISTORY_ID),
  CONSTRAINT FK_BOOK_HIS_BOOKS_BOOKSINFO FOREIGN KEY (BOOKS_ID)
    REFERENCES BOOKS(BOOKS_ID),
  CONSTRAINT FK_BOOK_HISTORY_MEMBERS_AUTHOR FOREIGN KEY (MEMBERS_ID)
    REFERENCES MEMBERS(MEMBERS_ID)
);

-- 인덱스 생성
CREATE INDEX IDX_BOOK_HISTORY_RENT_DATE   ON BOOK_HISTORY (LOAN_DATE);   -- 대여날짜순 정렬
CREATE INDEX IDX_BOOK_HISTORY_DUE_DATE    ON BOOK_HISTORY (DUE_DATE);    -- 반납예정일자순 정렬
CREATE INDEX IDX_BOOK_HISTORY_IS_OVERDUE  ON BOOK_HISTORY (IS_OVERDUE);  -- 연체여부 필터

-- 시퀀스 생성
CREATE SEQUENCE SQ_BOOK_HISTORY
START WITH 1
INCREMENT BY 1
NOMAXVALUE
NOCYCLE
NOCACHE;