-- 테이블 생성
CREATE TABLE CARDNUM_SERIAL (
	CARDNUM_SERIAL_ID NUMBER PRIMARY KEY,
    CURRENT_DATE DATE NOT NULL, -- 날짜
    SERIAL NUMBER(6) NOT NULL -- 일련번호
);

-- 테이블 전체 조회
SELECT * FROM CARDNUM_SERIAL;

-- 데이터 추가
INSERT INTO CARDNUM_SERIAL (CARDNUM_SERIAL_ID, CURRENT_DATE, SERIAL)
VALUES (1, SYSDATE, 1);

-- 테이블 내용 전체 삭제
TRUNCATE TABLE CARDNUM_SERIAL;

-- 테이블 제거
DROP TABLE CARDNUM_SERIAL;

